[api]
hypixel = ""
discord = ""

[db]
host = ""
username = ""
password = ""
database = ""

[options] # Will be replaced with in guild options
wiki-link = false
min-time = 500
min-profit = 200_000
add-recombobulator = false
use-custom-protocol = false  # Leave this false unless you know what you are doing